---
title: "Canli Sonuclar"
author: "Kadir Jun Ayhan"
format: html
editor: visual
---

# Libraries

```{r}
library(ggplot2)
library(tidyverse)
library(ggthemes)
library(magrittr)
```

# Sonuclar

```{r}
df <- read.csv("data/AA_vs_ANKA.csv")

df %<>% mutate(rte2 = RTE/(RTE+KK),
               kk2 = KK/(RTE+KK)) %>%
  select(-RTE, -KK)

df2 <- tibble::tribble(
  ~Ajans, ~Sandik, ~rte2, ~kk2, ~tur,
  "AA", 5.2, 0.675, 0.325, 2,
  "AA", 7.43, 0.6601, 0.3399, 2,
  "AA", 11.46, 0.6404, 0.3596, 2,
  "AA", 13.48, 0.6309, 0.3691, 2,
  "AA", 20.6, 0.608, 0.391, 2,
  "AA", 20.85, 0.6077, 0.3923, 2,
  "AA", 27.02, 0.5943, 0.4057, 2,
  "AA", 33, 0.583, 0.416, 2,
  "ANKA", 7.19, 0.4957, 0.5043, 2,
  "ANKA", 9.19, 0.4953, 0.5047, 2,
  "ANKA", 17.44, 0.4944, 0.5056, 2,
  "ANKA", 24.81, 0.4926, 0.5074, 2,
  "ANKA", 36.6, 0.4908, 0.5092, 2,
  "AA", 42.78, 0.5709, 0.4291, 2,
  "ANKA", 41, 0.4914, 0.5086, 2,
  "ANKA", 44.6, 0.4904, 0.5096, 2,
  "ANKA", 48.4, 0.4895, 0.5105, 2,
  "AA", 49.39, 0.5636, 0.4364, 2,
  "ANKA", 51.8, 0.4888, 0.5112, 2,
  "AA", 55.1, 0.558, 0.442, 2,
  "ANKA", 55.7, 0.4896, 0.5104, 2,
  "AA", 61.38, 0.5526, 0.4474, 2,
  "ANKA", 59.5, 0.4901, 0.5099, 2,
  "ANKA", 62.2, 0.4896, 0.5104, 2,
  "AA", 66.65, 0.5478, 0.4522, 2,
  "ANKA", 65.7, 0.4907, 0.5093, 2,
  "ANKA", 68.7, 0.4913, 0.5087, 2,
  "ANKA", 70.9, 0.4912, 0.5088, 2,
  "AA", 71.4, 0.5437, 0.4563, 2,
  "AA", 75.6, 0.5403, 0.4597, 2,
  "ANKA", 75.3, 0.4919, 0.5081, 2,
  "ANKA", 79.3, 0.4987, 0.5013, 2,
  "AA", 79.09, 0.537, 0.463, 2,
  "ANKA", 81.2, 0.4993, 0.5007, 2,
  "AA", 82.64, 0.5341, 0.4659, 2,
  "ANKA", 83.9, 0.4999, 0.5001, 2,
  "AA", 85.45, 0.5315, 0.4685, 2,
  "ANKA", 84.8, 0.5, 0.5, 2,
  "ANKA", 87.8, 0.506, 0.494, 2,
  "AA", 87.55, 0.5293, 0.4707, 2,
  "ANKA", 89.5, 0.5067, 0.4933, 2,
  "AA", 89.8, 0.5272, 0.4728, 2,
  "AA", 91.6, 0.5261, 0.4739, 2,
  "ANKA", 91.1, 0.5081, 0.4919, 2,
  "AA", 93, 0.525, 0.475, 2,
  "ANKA", 93.4, 0.5135, 0.4865, 2,
  "AA", 94.1, 0.5243, 0.4757, 2,
  "ANKA", 94.3, 0.5142, 0.4858, 2,
  "ANKA", 95.1, 0.515, 0.485, 2,
  "AA", 95.24, 0.5234, 0.4766, 2,
  "AA", 96.6, 0.5224, 0.4776, 2,
  "ANKA", 96.7, 0.518, 0.482, 2
)

df_new <- rbind(df, df2)


number_ticks <- function(n) {function(limits) pretty(limits, n)}

df_new %>% 
  ggplot(aes(x = Sandik)) +
  geom_line(aes(y = kk2, color = "kk2"), linetype = "solid") +
  geom_line(aes(y = rte2, color = "rte2"), linetype = "solid") +
  #scale_y_continuous(breaks = number_ticks(10)) +
  scale_y_continuous(breaks = scales::pretty_breaks(n = 6)) +
  #geom_text(aes(y = rte2, label = rte2), hjust = -0.2, vjust = -0.5, color = "blue") +
  #geom_text(aes(y = kk2, label = kk2), hjust = -0.2, vjust = 1, color = "red") +
  facet_wrap(vars(Ajans, tur)) +
  labs(x = "Acilan Sandik Orani
  Not: Ilk turdaki diger adaylarin oylari dagitilmistir", y = "Oy orani", color = "Legend title") +
  scale_color_manual(values = c("kk2" = "red", "rte2" = "blue"),
                     labels = c("Kilicdaroglu", "Erdogan"),
                     name = "Aday") +
  theme(legend.position="bottom")  +
  theme_economist()

ggsave("live results/2.tur v.10.jpg", dpi = 300)
```

# 
